version: "3.8"

services:
  subsai-webui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    volumes:
      - ./data:/subsai/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  subsai-webui-cpu:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8502:8501"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    volumes:
      - ./data:/subsai/data
