version: "3.8"

services:
  subsai-webui:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    ports:
      - "8501:8501"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - SUBSAI_DB_PATH=/subsai/data/subsai_auth.db
      - DOCKER_ENV=true
    volumes:
      - ./data:/subsai/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
