version: "3.8"

services:
  subsai-webui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - SUBSAI_DB_PATH=/subsai/data/subsai_auth.db
    volumes:
      - ./data:/subsai/data
